stages:
  - sonarlint

sonarlint:
  stage: sonarlint
  image:
    # https://gitlab.com/4s1/docker/-/blob/main/sonarlint-cli/Dockerfile
    name: registry.gitlab.com/4s1/docker/sonarlint-cli:latest
    entrypoint: ['']
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || ($CI_PIPELINE_SOURCE == "merge_request_event" && $CI_COMMIT_REF_NAME !~ /^renovate\//)
      when: on_success
    - when: never
  cache:
    key: '${CI_JOB_NAME}'
    paths:
      - .sonar/cache
  variables:
    # Defines the location of the analysis task cache
    SONAR_USER_HOME: '${CI_PROJECT_DIR}/.sonar'
    # Tells git to fetch all the branches of the project, required by the analysis task
    GIT_DEPTH: '0'
    # clone entire repo instead of reusing workspace
    # - https://gitlab.com/gitlab-org/gitlab/-/issues/292470
    # - https://gitlab.com/gitlab-org/gitlab/-/issues/350100
    GIT_STRATEGY: 'clone'
  script:
    - sonar-scanner
