stages:
  - validate

validate:
  stage: validate
  # https://gitlab.com/4s1/docker/-/blob/main/node/alpine/dev/Dockerfile
  image: registry.gitlab.com/4s1/docker/node:14-alpine-dev
  variables:
    # required by ava (https://github.com/avajs/ava/blob/main/docs/08-common-pitfalls.md#ava-in-docker)
    CI: 'true'
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - if: '$CI_COMMIT_TAG != null'
      when: never
    - when: always
  cache:
    key: '$CI_COMMIT_REF_SLUG'
    paths:
      - .pnpm-store
  artifacts:
    paths:
      - coverage/
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  script:
    - pnpm i
    - pnpm run lint
    - pnpm run build
    - pnpm run test:cov
